name: Run Spring Boot Tests

on:
  push:
    branches:
      - main  # O especifica la rama que prefieras
  pull_request: # Opcional: para ejecutar las pruebas en pull requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuración de JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # O 'zulu' o 'adopt' según prefieras
        java-version: '17' # Cambia según la versión que uses en tu proyecto

    # 3. Cache de dependencias de Maven
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    # 4. Compilación y ejecución de tests
    - name: Run tests
      run: mvn test
